language: cpp
os:
 - osx

before_install:
 - brew update
 - brew install qt
 - brew info qt

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make
 - cat /Users/travis/build/alexallmont/MinimalQt/build/CMakeFiles/CMakeOutput.log
